### ISSUE TITLE
new layout loaded all_posts length: 3 no post_url, skipping no post_url, skipping no post_url, skipping

### ISSUE THREAD

**Issue by moh-ddroid** [moda20/facebook_page_scraper#5]
when i run the code 
it keeps doing this [WDM] - Driver [C:\Users\pc\.wdm\drivers\geckodriver\win64\v0.35.0\geckodriver.exe] found in cache
new layout loaded
all_posts length: 3
no post_url, skipping
no post_url, skipping
no post_url, skipping 
i tried yours and the original one as well

**Comment by moda20** [comment]
@moh-ddroid is this still an issue, i updated the repo to fix it some time ago. 
please reopen if it is still.

**Comment by Irene933** [comment]
Yes it is still an issue!
